import { WCAG_LARGE_TEXT_RATIO, WCAG_AA_RATIO, WCAG_AAA_RATIO } from "./accessibility";

import { SLIDER_RANGES, DEFAULT_MODES_CONFIG } from "./color-palette-settings";

import {
  EXPORT_COLOR_SPACES,
  DEFAULT_EXPORT_COLOR_SPACE,
  COLOR_PICKER_SIZE,
  DEFAULT_EXPORT_FORMAT,
  EXPORT_FORMATS,
  EXPORT_FORMATS_VALUES,
  POPOVER_HEIGHT,
  POPOVER_OFFSET,
  POPOVER_WIDTH,
} from "./export";

import { ICON_SIZES } from "./icon";

import { COLOR_STEP_COUNT, STEP_GROUPS, NUMERIC_LABELS, SEMANTIC_NAMES, NUMERIC_LABELS_INDEXES } from "./radix-step";

import { COLOR_SPACES, COLOR_SPACES_VALUES, BLACK, WHITE } from "./color";
import { APPEARANCES, DEFAULT_APPEARANCE } from "./appearance";
import {
  MAIN_VIEWS,
  DEFAULT_MAIN_VIEW,
  FAB_PANEL_TABS,
  DEFAULT_FAB_PANEL_TAB,
  FAB_PANEL_TABS_VALUES,
  MAIN_VIEWS_VALUES,
} from "./views";

export {
  // ACCESSIBILITY
  WCAG_LARGE_TEXT_RATIO,
  WCAG_AA_RATIO,
  WCAG_AAA_RATIO,

  // RADIX PHILOSOPHY STEP
  COLOR_STEP_COUNT,
  STEP_GROUPS,
  NUMERIC_LABELS_INDEXES,
  NUMERIC_LABELS,
  SEMANTIC_NAMES,

  // COLOR
  BLACK,
  WHITE,

  // COLOR SPACES
  COLOR_SPACES,
  COLOR_SPACES_VALUES,

  // COLOR PALETTE SETTINGS
  SLIDER_RANGES,
  DEFAULT_MODES_CONFIG,

  // COLOR EXPORT SETTINGS
  EXPORT_COLOR_SPACES,
  DEFAULT_EXPORT_COLOR_SPACE,
  COLOR_PICKER_SIZE,
  EXPORT_FORMATS_VALUES,
  DEFAULT_EXPORT_FORMAT,
  EXPORT_FORMATS,
  POPOVER_HEIGHT,
  POPOVER_OFFSET,
  POPOVER_WIDTH,

  // ICONS
  ICON_SIZES,

  // APPEARANCES
  APPEARANCES,
  DEFAULT_APPEARANCE,

  // VIEWS
  FAB_PANEL_TABS,
  DEFAULT_FAB_PANEL_TAB,
  FAB_PANEL_TABS_VALUES,
  MAIN_VIEWS,
  DEFAULT_MAIN_VIEW,
  MAIN_VIEWS_VALUES,
};
